package com.example.coroutines.model

data class GithubUser(
	val gistsUrl: String,
	val reposUrl: String,
	val followingUrl: String,
	val twitterUsername: Any,
	val bio: Any,
	val createdAt: String,
	val login: String,
	val type: String,
	val blog: String,
	val subscriptionsUrl: String,
	val updatedAt: String,
	val siteAdmin: Boolean,
	val company: Any,
	val id: Int,
	val publicRepos: Int,
	val gravatarId: String,
	val email: Any,
	val organizationsUrl: String,
	val hireable: Any,
	val starredUrl: String,
	val followersUrl: String,
	val publicGists: Int,
	val url: String,
	val receivedEventsUrl: String,
	val followers: Int,
	val avatarUrl: String,
	val eventsUrl: String,
	val htmlUrl: String,
	val following: Int,
	val name: String,
	val location: String,
	val nodeId: String
)
